-- Queue.ai — PENDING migrations bundle (apply in Supabase SQL Editor).
-- Order: 0019, 0021 → 0029. All idempotent (safe to re-run).
-- Generated by scripts; source of truth = supabase/migrations/*.
begin;

-- ════════════════════════════════════════════════════════
-- 0019_flow_intelligence_v2.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0019 Flow Intelligence v2 (Phase 16.5): Predictive Operations (F13),
-- Capacity AI (F2), and Simulation (F5) — heuristic now, improves with pilot data.
-- All computed live from the queue + staff state; honest estimates (labeled in UI).

-- Predictive Operations: per-department forward look + a recommended action.
create or replace function public.get_predictive_ops(p_branch_id uuid, p_threshold_min int default 20)
returns jsonb language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_out jsonb;
begin
  select organization_id into v_org from branches where id = p_branch_id;
  if v_org is null or v_org <> app.current_org() then raise exception 'forbidden'; end if;

  select coalesce(jsonb_agg(w order by (w->>'clear_min')::numeric desc), '[]'::jsonb) into v_out
  from (
    select jsonb_build_object(
      'department', d.name,
      'waiting', wq.waiting,
      'servers', wq.servers,
      'clear_min', round(wq.clear_s / 60.0),
      'recommend', 'Move 1 staff to ' || d.name || ' (or open a counter)',
      'projected_clear_min', round((wq.waiting * wq.avg_s) / ((wq.servers + 1)) / 60.0)
    ) as w
    from departments d
    join lateral (
      select
        count(vs.id) filter (where vs.state = 'active') as waiting,
        greatest((select count(*) from staff s
                   where s.department_id = d.id and s.status = 'online' and s.deleted_at is null), 1) as servers,
        coalesce((select avg(sv.avg_duration_seconds) from services sv where sv.department_id = d.id), 600) as avg_s,
        (count(vs.id) filter (where vs.state = 'active')
           * coalesce((select avg(sv.avg_duration_seconds) from services sv where sv.department_id = d.id), 600))
          / greatest((select count(*) from staff s
                       where s.department_id = d.id and s.status = 'online' and s.deleted_at is null), 1) as clear_s
      from visit_stages vs
      join visits v on v.id = vs.visit_id and v.branch_id = p_branch_id
      where vs.department_id = d.id
    ) wq on true
    where d.branch_id = p_branch_id
      and wq.clear_s / 60.0 > p_threshold_min          -- only surface real risks
  ) sub;
  return v_out;
end $$;
grant execute on function public.get_predictive_ops(uuid, int) to authenticated;

-- Simulation: project branch-wide avg wait under a staffing change (what-if).
create or replace function public.simulate_branch(p_branch_id uuid, p_add_staff int default 0, p_remove_staff int default 0)
returns jsonb language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_wait int; v_servers int; v_avg numeric; v_new int; v_cur_min numeric; v_proj_min numeric;
begin
  select organization_id into v_org from branches where id = p_branch_id;
  if v_org is null or v_org <> app.current_org() then raise exception 'forbidden'; end if;

  select count(*) into v_wait from visit_stages vs join visits v on v.id = vs.visit_id
   where v.branch_id = p_branch_id and vs.state = 'active';
  select greatest(count(*),1) into v_servers from staff s join departments d on d.id = s.department_id
   where d.branch_id = p_branch_id and s.status = 'online' and s.deleted_at is null;
  select coalesce(avg(sv.avg_duration_seconds), 600) into v_avg from services sv
   join departments d on d.id = sv.department_id where d.branch_id = p_branch_id;

  v_new := greatest(v_servers + p_add_staff - p_remove_staff, 1);
  v_cur_min  := round((v_wait * v_avg) / v_servers / 60.0, 1);
  v_proj_min := round((v_wait * v_avg) / v_new     / 60.0, 1);

  return jsonb_build_object(
    'waiting', v_wait, 'servers', v_servers, 'new_servers', v_new,
    'current_avg_wait_min', v_cur_min, 'projected_avg_wait_min', v_proj_min,
    'delta_pct', case when v_cur_min > 0 then round((v_proj_min - v_cur_min) / v_cur_min * 100) else 0 end
  );
end $$;
grant execute on function public.simulate_branch(uuid, int, int) to authenticated;

-- ════════════════════════════════════════════════════════
-- 0021_staff_status_rpc.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0021 (audit H4): staff status via an event-emitting RPC.
-- Was a direct table write → no activity_event, no ETA-impact signal (broke 06 §4 + OPS-3).

create or replace function public.set_staff_status(p_status staff_status)
returns void language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_staff uuid; v_before staff_status;
begin
  select id, organization_id, status into v_staff, v_org, v_before
  from staff where user_id = auth.uid() and deleted_at is null limit 1;
  if v_staff is null then raise exception 'not a staff member'; end if;

  update staff set status = p_status, updated_at = now() where id = v_staff;
  -- the event lets the worker recompute ETAs / notify affected patients (OPS-3)
  perform app.log_event(v_org, null, 'staff', v_staff, 'staff_status', v_before::text, p_status::text);
end $$;
grant execute on function public.set_staff_status(staff_status) to authenticated;

-- ════════════════════════════════════════════════════════
-- 0022_phone_encryption.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0022 (audit C2 + H3): encrypt patient phone at rest + rate-limit public join.
-- C2: phone stored as pgcrypto-encrypted bytea + HMAC blind index for unique lookup.
--     Decrypt key lives in app.crypto_key (locked down); only SECURITY DEFINER funcs use it.
-- H3: join_queue throttles repeat joins per phone+branch (anti-spam/DoS).

-- ── Key store (no direct access by app roles) ──────────────────────────────────
create table if not exists app.crypto_key (id int primary key default 1, key bytea not null);
insert into app.crypto_key (id, key) values (1, gen_random_bytes(32)) on conflict (id) do nothing;
revoke all on app.crypto_key from public;

-- ── Crypto helpers (definer; key never leaves these functions) ─────────────────
-- NOTE: pgcrypto lives in the `extensions` schema on Supabase (in `public` on a bare
-- Postgres). Include both in search_path so pgp_sym_*/hmac resolve in either env.
create or replace function app.enc(p text) returns bytea
  language sql security definer set search_path = app, public, extensions as
$$ select pgp_sym_encrypt(p, encode((select key from app.crypto_key where id=1),'hex')) $$;

create or replace function app.dec(p bytea) returns text
  language sql security definer set search_path = app, public, extensions as
$$ select case when p is null then null
              else pgp_sym_decrypt(p, encode((select key from app.crypto_key where id=1),'hex')) end $$;

create or replace function app.bidx(p text) returns text
  language sql security definer set search_path = app, public, extensions as
$$ select encode(hmac(p, encode((select key from app.crypto_key where id=1),'hex'), 'sha256'),'hex') $$;

-- masked display for staff (last 4 only) — the only crypto helper app roles may call
create or replace function app.phone_last4(p bytea) returns text
  language sql security definer set search_path = app, public, extensions as
$$ select case when p is null then null else '••••' || right(app.dec(p), 4) end $$;

-- 0020 default-grants new app functions to anon/authenticated; lock the sensitive ones back down
revoke execute on function app.enc(text)  from anon, authenticated;
revoke execute on function app.dec(bytea) from anon, authenticated;
revoke execute on function app.bidx(text) from anon, authenticated;
revoke execute on function app.phone_last4(bytea) from anon;        -- staff only
grant  execute on function app.phone_last4(bytea) to authenticated;

-- ── Migrate customers.phone → encrypted columns ───────────────────────────────
alter table customers add column if not exists phone_enc  bytea;
alter table customers add column if not exists phone_bidx text;
update customers set phone_enc = app.enc(phone), phone_bidx = app.bidx(phone)
  where phone is not null and phone_bidx is null;
alter table customers drop constraint if exists customers_phone_key;
-- reception_queue (0011) reads customers.phone; drop it first, recreated below with phone_last4
drop view if exists reception_queue;
alter table customers drop column if exists phone;
create unique index if not exists customers_phone_bidx_key on customers (phone_bidx);

-- ── Rewrite join RPCs to use enc/bidx (+ H3 throttle) ─────────────────────────
create or replace function public.join_queue(
  p_branch_token text, p_flow_id uuid, p_name text, p_phone text,
  p_channel join_channel default 'web', p_immediate boolean default false
) returns uuid language plpgsql security definer set search_path = public, app as $$
declare
  v_org uuid; v_branch uuid; v_ver uuid; v_cust uuid; v_link uuid; v_visit uuid;
  v_first uuid; r record; first_done boolean := false; v_state stage_state; v_pos int; v_recent int;
begin
  select id, organization_id into v_branch, v_org from branches where qr_token = p_branch_token;
  if v_branch is null then raise exception 'branch not found'; end if;

  if p_flow_id is null then
    select id into p_flow_id from flows where organization_id = v_org and is_published order by created_at limit 1;
  end if;
  select current_version_id into v_ver from flows where id = p_flow_id and organization_id = v_org;
  if v_ver is null then raise exception 'no published flow'; end if;

  insert into customers (phone_enc, phone_bidx, full_name)
    values (app.enc(p_phone), app.bidx(p_phone), p_name)
    on conflict (phone_bidx) do update set full_name = coalesce(excluded.full_name, customers.full_name)
    returning id into v_cust;
  insert into customer_org_link (organization_id, customer_id) values (v_org, v_cust)
    on conflict (organization_id, customer_id)
      do update set last_seen = now(), visit_count = customer_org_link.visit_count + 1
    returning id into v_link;

  -- H3: throttle repeat joins (max 3 per phone per branch / 2 min)
  select count(*) into v_recent from visits v
    where v.customer_org_link_id = v_link and v.branch_id = v_branch
      and v.created_at > now() - interval '2 minutes';
  if v_recent >= 3 then raise exception 'too many requests — please wait a moment'; end if;

  insert into visits (organization_id, branch_id, customer_org_link_id, flow_version_id, channel)
    values (v_org, v_branch, v_link, v_ver, p_channel) returning id into v_visit;

  for r in select id, department_id from flow_stages where flow_version_id = v_ver order by position loop
    if not first_done then
      if p_immediate then v_state := 'active'; v_pos := app.next_position(v_org, r.department_id);
      else v_state := 'pre_queue'; v_pos := null; end if;
      insert into visit_stages
        (organization_id, visit_id, flow_stage_id, department_id, state, position,
         entered_state_at, pre_queue_at, activated_at, activation_trigger, is_current)
      values (v_org, v_visit, r.id, r.department_id, v_state, v_pos, now(), now(),
              case when p_immediate then now() else null end,
              case when p_immediate then 'qr'::activation_trigger else null end, true)
      returning id into v_first;
      first_done := true;
    else
      insert into visit_stages (organization_id, visit_id, flow_stage_id, department_id, state)
      values (v_org, v_visit, r.id, r.department_id, 'booked');
    end if;
  end loop;

  perform app.log_event(v_org, v_branch, 'visit_stage', v_first, 'state_change', null, v_state::text,
                        jsonb_build_object('reason','self_join','channel',p_channel));
  return v_visit;
end $$;
grant execute on function public.join_queue(text,uuid,text,text,join_channel,boolean) to anon, authenticated;

create or replace function public.create_walkin_visit(
  p_branch_id uuid, p_flow_id uuid, p_name text, p_phone text, p_acuity acuity default 'routine'
) returns uuid language plpgsql security definer set search_path = public, app as $$
declare
  v_org uuid; v_ver uuid; v_cust uuid; v_link uuid; v_visit uuid;
  v_first uuid; r record; v_pos int; first_done boolean := false;
begin
  select organization_id into v_org from branches where id = p_branch_id;
  if v_org is null or v_org <> app.current_org() then raise exception 'forbidden'; end if;
  if p_flow_id is null then
    select id into p_flow_id from flows where organization_id = v_org and is_published order by created_at limit 1;
  end if;
  select current_version_id into v_ver from flows where id = p_flow_id;
  if v_ver is null then raise exception 'no published flow'; end if;

  insert into customers (phone_enc, phone_bidx, full_name)
    values (app.enc(p_phone), app.bidx(p_phone), p_name)
    on conflict (phone_bidx) do update set full_name = coalesce(excluded.full_name, customers.full_name)
    returning id into v_cust;
  insert into customer_org_link (organization_id, customer_id) values (v_org, v_cust)
    on conflict (organization_id, customer_id)
      do update set last_seen = now(), visit_count = customer_org_link.visit_count + 1
    returning id into v_link;

  insert into visits (organization_id, branch_id, customer_org_link_id, flow_version_id, acuity, channel)
    values (v_org, p_branch_id, v_link, v_ver, p_acuity, 'receptionist') returning id into v_visit;

  for r in select fs.id, fs.department_id from flow_stages fs where fs.flow_version_id = v_ver order by fs.position loop
    if not first_done then
      v_pos := app.next_position(v_org, r.department_id);
      insert into visit_stages
        (organization_id, visit_id, flow_stage_id, department_id, state, position, acuity,
         entered_state_at, pre_queue_at, activated_at, activation_trigger, is_current)
      values (v_org, v_visit, r.id, r.department_id, 'active', v_pos, p_acuity,
              now(), now(), now(), 'receptionist', true)
      returning id into v_first;
      first_done := true;
    else
      insert into visit_stages (organization_id, visit_id, flow_stage_id, department_id, state, acuity)
      values (v_org, v_visit, r.id, r.department_id, 'booked', p_acuity);
    end if;
  end loop;

  perform app.log_event(v_org, p_branch_id, 'visit_stage', v_first, 'state_change', null, 'active',
                        jsonb_build_object('reason','walkin_created'));
  return v_visit;
end $$;
grant execute on function public.create_walkin_visit(uuid,uuid,text,text,acuity) to authenticated;

-- ── reception_queue: mask phone (last 4 only) ─────────────────────────────────
create or replace view reception_queue with (security_invoker = true) as
select
  vs.id as stage_id, vs.organization_id, v.branch_id, vs.department_id, d.name as department_name,
  vs.visit_id, vs.state, vs.acuity, vs.position, vs.entered_state_at, vs.grace_deadline,
  upper(substr(replace(vs.id::text,'-',''),1,6)) as ticket_no,
  c.full_name as patient_name,
  app.phone_last4(c.phone_enc) as patient_phone
from visit_stages vs
join visits v on v.id = vs.visit_id
join departments d on d.id = vs.department_id
left join customer_org_link l on l.id = v.customer_org_link_id
left join customers c on c.id = l.customer_id
where vs.state in ('active','called','serving');

-- ════════════════════════════════════════════════════════
-- 0023_intelligence_rollups.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0023 (audit H1 + M5): populate the intelligence/metric backbone.
-- Worker (service_role) calls these on a schedule. Turns the empty tables into real
-- history → Flow Score trend, Capacity AI/Org-Memory data source, cheaper dashboards.
-- (Per-staff throughput needs assigned-staff capture; for now we roll up per department.)

create or replace function public.rollup_throughput(p_window_min int default 60)
returns int language plpgsql security definer set search_path = public, app as $$
declare n int := 0; r record;
begin
  for r in
    select vs.organization_id, vs.department_id,
           count(*) c, avg(extract(epoch from (vs.completed_at - vs.serving_at)))::int avg_s
    from visit_stages vs
    where vs.completed_at > now() - make_interval(mins => p_window_min)
      and vs.serving_at is not null
    group by vs.organization_id, vs.department_id
  loop
    insert into staff_throughput
      (organization_id, staff_id, department_id, window_start, window_end, served_count, avg_service_seconds, idle_seconds)
    values (r.organization_id, null, r.department_id,
            now() - make_interval(mins => p_window_min), now(), r.c, r.avg_s, 0);
    n := n + 1;
  end loop;
  return n;
end $$;
grant execute on function public.rollup_throughput(int) to service_role;

create or replace function public.rollup_daily_metrics()
returns int language plpgsql security definer set search_path = public, app as $$
declare n int := 0; b record;
        v_avg numeric; v_served int; v_created int; v_noshow int; v_done int;
        v_nsr numeric; v_wp numeric; v_comp numeric; v_score int; v_saved bigint;
begin
  for b in select id, organization_id,
                  coalesce((settings->>'baseline_wait_seconds')::int, 2400) baseline from branches loop
    select coalesce(avg(extract(epoch from (vs.called_at - vs.activated_at))), 0) into v_avg
      from visit_stages vs join visits v on v.id = vs.visit_id
      where v.branch_id = b.id and vs.called_at >= current_date and vs.activated_at is not null;
    select count(*) into v_served from visits where branch_id = b.id and status='completed' and completed_at >= current_date;
    select count(*) into v_created from visits where branch_id = b.id and created_at >= current_date;
    select count(*) into v_noshow from visit_stages vs join visits v on v.id = vs.visit_id
      where v.branch_id = b.id and vs.state='no_show' and vs.entered_state_at >= current_date;
    select count(*) into v_done from visit_stages vs join visits v on v.id = vs.visit_id
      where v.branch_id = b.id and vs.state='completed' and vs.completed_at >= current_date;

    v_nsr  := case when (v_noshow+v_done) > 0 then v_noshow::numeric/(v_noshow+v_done) else 0 end;
    v_wp   := least(b.baseline::numeric / greatest(v_avg,1), 1);
    v_comp := case when v_created > 0 then least(v_served::numeric/v_created, 1) else 1 end;
    v_score := round(100 * (0.5*v_wp + 0.25*(1-v_nsr) + 0.25*v_comp));
    v_saved := greatest(0, v_served * (b.baseline - round(v_avg)));

    insert into daily_metrics
      (organization_id, branch_id, metric_date, flow_score, avg_wait_seconds, no_show_rate, time_saved_seconds)
    values (b.organization_id, b.id, current_date, v_score, round(v_avg), round(v_nsr,4), v_saved)
    on conflict (branch_id, metric_date) do update set
      flow_score = excluded.flow_score, avg_wait_seconds = excluded.avg_wait_seconds,
      no_show_rate = excluded.no_show_rate, time_saved_seconds = excluded.time_saved_seconds;
    n := n + 1;
  end loop;
  return n;
end $$;
grant execute on function public.rollup_daily_metrics() to service_role;

-- ════════════════════════════════════════════════════════
-- 0024_consistency_helpers.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0024 (audit M1/M2/M5): single transition authority, baseline helper,
-- and rollup-backed Hours Returned (stop scanning all history per dashboard load).

-- M1 — canonical state-machine transitions in SQL (mirrors packages/shared STAGE_TRANSITIONS).
create or replace function app.can_transition(p_from stage_state, p_to stage_state)
returns boolean language sql immutable as $$
  select (p_from, p_to) in (
    ('booked','pre_queue'), ('booked','active'), ('booked','cancelled'), ('booked','expired'),
    ('pre_queue','active'), ('pre_queue','cancelled'), ('pre_queue','expired'),
    ('active','called'), ('active','cancelled'),
    ('called','serving'), ('called','no_show'), ('called','active'),
    ('serving','completed'), ('serving','transferred'), ('serving','active'),
    ('transferred','active')
  )
$$;
create or replace function app.assert_transition(p_from stage_state, p_to stage_state)
returns void language plpgsql as $$
begin
  if not app.can_transition(p_from, p_to) then
    raise exception 'illegal stage transition: % -> %', p_from, p_to;
  end if;
end $$;

-- M2 — single source for a branch's baseline wait (was duplicated in 4 functions).
create or replace function app.branch_baseline(p_branch uuid)
returns int language sql stable as $$
  select coalesce((settings->>'baseline_wait_seconds')::int, 2400) from branches where id = p_branch
$$;

-- M5 — Hours Returned reads pre-aggregated daily_metrics (cheap) + live "today",
-- instead of scanning every visit in history on each dashboard load.
create or replace function public.get_hours_returned(p_branch_id uuid)
returns jsonb language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_baseline int; v_today bigint; v_month bigint; v_life bigint;
begin
  select organization_id into v_org from branches where id = p_branch_id;
  if v_org is null or v_org <> app.current_org() then raise exception 'forbidden'; end if;
  v_baseline := app.branch_baseline(p_branch_id);

  v_today := app.hours_returned_since(p_branch_id, v_baseline, current_date);
  v_month := coalesce((select sum(time_saved_seconds) from daily_metrics
              where branch_id = p_branch_id
                and metric_date >= date_trunc('month', now())::date
                and metric_date < current_date), 0) + v_today;
  v_life  := coalesce((select sum(time_saved_seconds) from daily_metrics
              where branch_id = p_branch_id and metric_date < current_date), 0) + v_today;

  return jsonb_build_object('today_seconds', v_today, 'month_seconds', v_month, 'lifetime_seconds', v_life);
end $$;
grant execute on function public.get_hours_returned(uuid) to authenticated;

-- ════════════════════════════════════════════════════════
-- 0025_queue_verbs.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0025 (compliance gap): transfer / delay / requeue / skip verbs.
-- Completes the staff/reception action set (wireframe S1). Uses app.assert_transition
-- (0024) as the single authority; each emits an activity_event (06 §4).

-- helper: activate a specific (booked) next stage, optionally overriding its department
create or replace function app.activate_next(p_visit uuid, p_org uuid, p_branch uuid, p_to_dept uuid default null)
returns uuid language plpgsql set search_path = public, app as $$
declare v_next uuid; v_dept uuid;
begin
  select ns.id, coalesce(p_to_dept, ns.department_id) into v_next, v_dept
  from visit_stages ns join flow_stages nfs on nfs.id = ns.flow_stage_id
  where ns.visit_id = p_visit and ns.state = 'booked'
  order by nfs.position asc limit 1;

  if v_next is null then
    update visits set status = 'completed', completed_at = now() where id = p_visit;
    perform app.log_event(p_org, p_branch, 'visit', p_visit, 'state_change', 'active', 'completed');
    return null;
  end if;

  update visit_stages set state = 'active', department_id = v_dept,
    position = app.next_position(p_org, v_dept), is_current = true,
    activated_at = now(), pre_queue_at = now(), entered_state_at = now(), activation_trigger = 'receptionist'
  where id = v_next;
  perform app.log_event(p_org, p_branch, 'visit_stage', v_next, 'state_change', 'booked', 'active',
                        jsonb_build_object('reason','advance'));
  return v_next;
end $$;

-- TRANSFER: finish current stage and route to the next (optionally to a chosen department)
create or replace function public.transfer_stage(p_stage_id uuid, p_to_department_id uuid default null)
returns uuid language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_visit uuid; v_branch uuid; v_from text;
begin
  v_org := app.current_org();
  select vs.visit_id, v.branch_id, vs.state::text into v_visit, v_branch, v_from
  from visit_stages vs join visits v on v.id = vs.visit_id
  where vs.id = p_stage_id and vs.organization_id = v_org and vs.state in ('serving','called','active') for update;
  if v_visit is null then raise exception 'stage not transferable'; end if;
  perform app.assert_transition(v_from::stage_state, 'transferred');

  update visit_stages set state = 'transferred', completed_at = now(), entered_state_at = now(), is_current = false
  where id = p_stage_id;
  perform app.log_event(v_org, v_branch, 'visit_stage', p_stage_id, 'state_change', v_from, 'transferred');
  return app.activate_next(v_visit, v_org, v_branch, p_to_department_id);
end $$;
grant execute on function public.transfer_stage(uuid, uuid) to authenticated;

-- DELAY: send a serving/called stage back to the active queue (re-positioned at the end)
create or replace function public.delay_stage(p_stage_id uuid)
returns void language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_branch uuid; v_from text; v_dept uuid;
begin
  v_org := app.current_org();
  select v.branch_id, vs.state::text, vs.department_id into v_branch, v_from, v_dept
  from visit_stages vs join visits v on v.id = vs.visit_id
  where vs.id = p_stage_id and vs.organization_id = v_org and vs.state in ('serving','called') for update;
  if v_branch is null then raise exception 'stage not delayable'; end if;
  perform app.assert_transition(v_from::stage_state, 'active');

  update visit_stages set state = 'active', position = app.next_position(v_org, v_dept),
    entered_state_at = now(), called_at = null, grace_deadline = null
  where id = p_stage_id;
  perform app.log_event(v_org, v_branch, 'visit_stage', p_stage_id, 'state_change', v_from, 'active',
                        jsonb_build_object('reason','delay'));
end $$;
grant execute on function public.delay_stage(uuid) to authenticated;

-- REQUEUE: a late-but-present patient (called → active) within the grace window (R4)
create or replace function public.requeue_stage(p_stage_id uuid)
returns void language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_branch uuid; v_dept uuid;
begin
  v_org := app.current_org();
  select v.branch_id, vs.department_id into v_branch, v_dept
  from visit_stages vs join visits v on v.id = vs.visit_id
  where vs.id = p_stage_id and vs.organization_id = v_org and vs.state = 'called' for update;
  if v_branch is null then raise exception 'stage not requeuable'; end if;

  update visit_stages set state = 'active', position = app.next_position(v_org, v_dept),
    entered_state_at = now(), called_at = null, grace_deadline = null
  where id = p_stage_id;
  perform app.log_event(v_org, v_branch, 'visit_stage', p_stage_id, 'state_change', 'called', 'active',
                        jsonb_build_object('reason','requeue_in_grace'));
end $$;
grant execute on function public.requeue_stage(uuid) to authenticated;

-- SKIP: mark an optional stage skipped and advance (E5)
create or replace function public.skip_stage(p_stage_id uuid)
returns uuid language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_visit uuid; v_branch uuid; v_from text;
begin
  v_org := app.current_org();
  select vs.visit_id, v.branch_id, vs.state::text into v_visit, v_branch, v_from
  from visit_stages vs join visits v on v.id = vs.visit_id
  where vs.id = p_stage_id and vs.organization_id = v_org and vs.state in ('active','called','serving') for update;
  if v_visit is null then raise exception 'stage not skippable'; end if;

  update visit_stages set state = 'completed', skipped = true, completed_at = now(),
    entered_state_at = now(), is_current = false where id = p_stage_id;
  perform app.log_event(v_org, v_branch, 'visit_stage', p_stage_id, 'state_change', v_from, 'completed',
                        jsonb_build_object('reason','skipped'));
  return app.activate_next(v_visit, v_org, v_branch, null);
end $$;
grant execute on function public.skip_stage(uuid) to authenticated;

-- ════════════════════════════════════════════════════════
-- 0026_prediction_accuracy.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0026 (compliance gap, audit H1/07 §11): Trust-Engine accuracy loop.
-- Snapshot a prediction when a stage goes active; score it (actual vs band) when called.
-- Worker (service_role) runs these on a schedule → predictions table populated + calibratable.

alter table predictions add column if not exists actual_seconds int;
alter table predictions add column if not exists within_band   boolean;

-- snapshot ETA predictions for current active stages that don't have one yet
create or replace function public.snapshot_active_predictions()
returns int language plpgsql security definer set search_path = public, app as $$
declare n int := 0; r record;
        v_ahead int; v_servers int; v_avg int; v_pending int; v_eta int; v_conf numeric; v_half int;
begin
  for r in
    select vs.id, vs.organization_id, vs.department_id, vs.position, vs.acuity, v.branch_id, fs.est_duration_seconds
    from visit_stages vs
    join visits v on v.id = vs.visit_id
    join flow_stages fs on fs.id = vs.flow_stage_id
    where vs.state = 'active' and vs.is_current
      and not exists (select 1 from predictions p where p.visit_stage_id = vs.id)
  loop
    select count(*) into v_ahead from visit_stages a
      where a.department_id = r.department_id and a.state = 'active'
        and (a.acuity > r.acuity or (a.acuity = r.acuity and coalesce(a.position,0) < coalesce(r.position,0)));
    select greatest(count(*),1) into v_servers from staff s
      where s.department_id = r.department_id and s.status='online' and s.deleted_at is null;
    v_avg := coalesce(r.est_duration_seconds, 600);
    select coalesce(sum(fs.est_duration_seconds),0) into v_pending
      from visit_stages vs2 join flow_stages fs on fs.id = vs2.flow_stage_id
      where vs2.visit_id = (select visit_id from visit_stages where id = r.id) and vs2.state = 'booked';
    v_eta := (v_ahead * v_avg) / v_servers + v_pending;
    v_conf := 0.7;  -- snapshot confidence prior (calibrated over time from within_band rate)
    v_half := floor((1 - v_conf) * v_eta * 0.4);

    insert into predictions
      (organization_id, visit_stage_id, branch_id, department_id, kind, value_low_s, value_high_s, confidence, reasons)
    values (r.organization_id, r.id, r.branch_id, r.department_id, 'stage_eta',
            greatest(v_eta - v_half, 0), v_eta + v_half, v_conf,
            jsonb_build_array('snapshot at activation'));
    n := n + 1;
  end loop;
  return n;
end $$;
grant execute on function public.snapshot_active_predictions() to service_role;

-- score predictions once their stage has been called (actual wait known)
create or replace function public.score_pending_predictions()
returns int language plpgsql security definer set search_path = public, app as $$
declare n int := 0; r record; v_actual int;
begin
  for r in
    select p.id, vs.activated_at, vs.called_at, p.value_low_s, p.value_high_s
    from predictions p join visit_stages vs on vs.id = p.visit_stage_id
    where p.actual_seconds is null and vs.called_at is not null and vs.activated_at is not null
  loop
    v_actual := extract(epoch from (r.called_at - r.activated_at))::int;
    update predictions set actual_seconds = v_actual,
      within_band = (v_actual between coalesce(value_low_s,0) and coalesce(value_high_s, 2147483647))
    where id = r.id;
    n := n + 1;
  end loop;
  return n;
end $$;
grant execute on function public.score_pending_predictions() to service_role;

-- accuracy summary (for the Trust-Engine honesty metric: % within band)
create or replace function public.prediction_accuracy(p_branch_id uuid)
returns jsonb language plpgsql security definer set search_path = public, app as $$
declare v_org uuid; v_total int; v_hit int;
begin
  select organization_id into v_org from branches where id = p_branch_id;
  if v_org is null or v_org <> app.current_org() then raise exception 'forbidden'; end if;
  select count(*), count(*) filter (where within_band) into v_total, v_hit
  from predictions where branch_id = p_branch_id and actual_seconds is not null;
  return jsonb_build_object('scored', v_total, 'within_band', v_hit,
    'accuracy', case when v_total > 0 then round(v_hit::numeric/v_total, 3) else null end);
end $$;
grant execute on function public.prediction_accuracy(uuid) to authenticated;

-- ════════════════════════════════════════════════════════
-- 0027_sms_target.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0027 (compliance gap, R6): let the trusted worker resolve an SMS recipient.
-- Phone is encrypted (0022); the SMS provider needs the real number. This definer RPC
-- decrypts ONLY for service_role (the worker), keeping phones opaque to app roles.

create or replace function public.get_sms_target(p_notification_id uuid)
returns jsonb language sql security definer set search_path = public, app as $$
  select jsonb_build_object('phone', app.dec(c.phone_enc), 'event_type', n.event_type)
  from notifications n
  join customers c on c.id = n.customer_id
  where n.id = p_notification_id and c.phone_enc is not null
$$;
revoke execute on function public.get_sms_target(uuid) from anon, authenticated;
grant execute on function public.get_sms_target(uuid) to service_role;

-- ════════════════════════════════════════════════════════
-- 0028_gps_activation.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0028 (compliance gap, CTO-1): GPS geofence activation.
-- The client sends its coordinates; the geofence check + decision happen server-side
-- (branch coords never leave the DB). Activates the pre-queue stage only if within radius.

-- NOTE: PostGIS (st_distance/st_makepoint) lives in the `extensions` schema on Supabase;
-- include it in search_path so the spatial functions resolve there and on bare Postgres.
create or replace function public.activate_visit_gps(p_visit_id uuid, p_lat double precision, p_lng double precision)
returns jsonb language plpgsql security definer set search_path = public, app, extensions as $$
declare v_branch uuid; v_radius int; v_dist double precision; v_has_geo boolean;
begin
  select v.branch_id, b.geofence_radius_m, b.geo is not null
    into v_branch, v_radius, v_has_geo
  from visits v join branches b on b.id = v.branch_id
  where v.id = p_visit_id;
  if v_branch is null then raise exception 'visit not found'; end if;
  if not v_has_geo then return jsonb_build_object('ok', false, 'reason', 'no_geofence'); end if;

  select st_distance(b.geo, st_setsrid(st_makepoint(p_lng, p_lat), 4326)::geography)
    into v_dist from branches b where b.id = v_branch;

  if v_dist > v_radius then
    return jsonb_build_object('ok', false, 'reason', 'too_far', 'distance_m', round(v_dist));
  end if;

  perform public.activate_visit(p_visit_id, 'gps');
  return jsonb_build_object('ok', true, 'distance_m', round(v_dist));
end $$;
grant execute on function public.activate_visit_gps(uuid, double precision, double precision) to anon, authenticated;

-- ════════════════════════════════════════════════════════
-- 0029_public_queue.sql
-- ════════════════════════════════════════════════════════
-- Queue.ai — 0029 (F10): Anonymous Public Queue.
-- A no-PII, opt-in (branches.publish_public_wait) wait board people can check
-- *before* coming in. Aggregates per department only — never a name or phone (R3).

create or replace function public.get_public_wait(p_branch_token text)
returns jsonb language plpgsql security definer set search_path = public, app as $$
declare v_branch uuid; v_name text; v_opt boolean; v_depts jsonb;
begin
  select id, name, publish_public_wait into v_branch, v_name, v_opt
  from branches where qr_token = p_branch_token and deleted_at is null;
  if v_branch is null then raise exception 'branch not found'; end if;
  if not coalesce(v_opt, false) then
    return jsonb_build_object('available', false, 'branch_name', v_name);
  end if;

  select coalesce(jsonb_agg(d_row order by d_row->>'department_name'), '[]'::jsonb) into v_depts
  from (
    select jsonb_build_object(
      'department_name', d.name,
      'waiting', count(*) filter (where vs.state = 'active'),
      'now_serving', (
        select upper(substr(replace(s.id::text,'-',''),1,6))
        from visit_stages s where s.department_id = d.id and s.state in ('called','serving')
        order by s.entered_state_at desc limit 1
      ),
      'est_wait_min', greatest(1, round(
        (count(*) filter (where vs.state = 'active'))
        * coalesce((select avg(fs.est_duration_seconds) from flow_stages fs where fs.department_id = d.id), 600)
        / greatest((select count(*) from staff st where st.department_id = d.id and st.status='online' and st.deleted_at is null), 1)
        / 60.0
      ))
    ) as d_row
    from departments d
    left join visit_stages vs on vs.department_id = d.id and vs.state in ('active','called','serving')
    where d.branch_id = v_branch
    group by d.id, d.name
  ) t;

  return jsonb_build_object('available', true, 'branch_name', v_name, 'departments', v_depts);
end $$;
grant execute on function public.get_public_wait(text) to anon, authenticated;

commit;
